name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: sudo apt-get install libgtk-4-1 gobject-introspection gir1.2-gtk-4.0 libgirepository1.0-dev
      - name: Build documentation
        run: make doc

